2D Iteration
In this demonstration, you'll see how to iterate through a 2D array used nested loops, and we'll be using our iterative skills to locate trees in this world!

Create the world


In [1]:
import numpy as np


In [3]:
world = np.array([ [0, 0, 0, 1, 0],
                   [0, 0, 0, 1, 0],
                   [0, 1, 1, 0, 0],
                   [0, 0, 0, 0, 1],
                   [1, 0, 0, 1, 0],
                   [1, 0, 0, 0, 0] ])
print(world)
print('\nThe shape of this array is: ' + str(world.shape))


[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 0 0]]

The shape of this array is: (6, 5)


In [4]:
def iterate2D(arr):
    for i in range(0,arr.shape[0]):
        for j in range(0,arr.shape[1]):
            print('Index ['+str(i)+']['+str(j)+'] = ' +str(world[i][j]))
print('\n')
iterate2D(world)



Index [0][0] = 0
Index [0][1] = 0
Index [0][2] = 0
Index [0][3] = 1
Index [0][4] = 0
Index [1][0] = 0
Index [1][1] = 0
Index [1][2] = 0
Index [1][3] = 1
Index [1][4] = 0
Index [2][0] = 0
Index [2][1] = 1
Index [2][2] = 1
Index [2][3] = 0
Index [2][4] = 0
Index [3][0] = 0
Index [3][1] = 0
Index [3][2] = 0
Index [3][3] = 0
Index [3][4] = 1
Index [4][0] = 1
Index [4][1] = 0
Index [4][2] = 0
Index [4][3] = 1
Index [4][4] = 0
Index [5][0] = 1
Index [5][1] = 0
Index [5][2] = 0
Index [5][3] = 0
Index [5][4] = 0


In [5]:
#Find the first tree, 1, in the world¶
# This function is similar to our iterate2D function,
# But looks for the first tree in the array and prints its location [x][y]
def first_tree(arr):
    for i in range(0,arr.shape[0]):
        for j in range(0,arr.shape[1]):
            if (arr[i][j]==1):
                print('First tree found at location: ['+str(i)+']['+str(j)+']')
                return 
print('\n')
first_tree(world)



First tree found at location: [0][3]
